# Generated by Django 4.2 on 2023-04-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='massage',
            new_name='message',
        ),
    ]
